config/routes.rb
Rails.application.routes.draw do
  root to: 'trainings#index'
  resources :trainings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/training.rb
class Training < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class TrainingsController < ApplicationController
  def index
    @trainings = Training.all
    @training = Training.new
  end

  def show
    @training = Training.find(params[:id])
  end

  def create
    Training.create(training_parameter)
    redirect_to trainings_path
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to trainings_path, notice: "削除しました"
  end

  def edit
    @training = Training.find(params[:id])
  end

  def update
    @training = Training.find(params[:id])
    if @training.update(training_parameter)
      redirect_to trainings_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  def training_parameter
    params.require(:training).permit(:type, :weight, :rep, :set, :datetime)
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def index
    @trainings = Training.all
    @training = Training.new
  end

  def create
    Training.create(training_parameter)
    redirect_to trainings_path
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to trainings_path, notice: "削除しました"
  end

  def update
    @training = Training.find(params[:id])
    if @training.update(training_parameter)
      redirect_to trainings_path, notice: "編集しました"
    end
  end

  def training_parameter
    params.require(:training).permit(:training_type, :weight, :rep, :set, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module TrainingsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/events/_form_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  日記を書く
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">日記を書く</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: @training, local: true) do |form| %>
        <div class="modal-body">
          <div class="title">
            <%= form.label :title, "タイトル" %>
            <%= form.text_field :title %>
          </div>

            <div class="time">
            <%= form.label :start_time, "開始時間" %>
            <%= form.datetime_select :start_time %>
          </div>

          <div class="content">
            <%= form.label :content, "内容" %>
            <%= form.text_field :content %>
          </div>
        </div>
        <div class="modal-footer">
          <div class="submit">
            <%= form.submit "Save changes", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>カレンダー</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.title %></td>
        <td><%= training.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', training %></td>
        <td><%= link_to 'Edit', edit_training_path(training.id) %></td>
        <td><%= link_to 'Destroy',training_path(training.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render 'form_modal' %>

<%= month_calendar trainings: @trainings do |date, trainings| %>
  <%= date.day %>

  <% trainings.each do |training| %>
    <div>
      <%= link_to training.title, training %>
    </div>
  <% end %>
<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @training.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @training.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @training.content %>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>年 <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trainings/_detail_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-dark btn-sm text-decoration-none" data-bs-toggle="modal" data-bs-target="#detail<%= training.id %>Modal">
  <% if training.training_type.blank? %>
    名称未登録
  <% else %>
    <%= training.training_type %>
  <% end %>
</button>

<!-- Modal -->
<div class="modal fade" id="detail<%= training.id %>Modal" tabindex="-1" aria-labelledby="detail<%= training.id %>ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="detail<%= training.id %>ModalLabel">記録</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: training, local: true) do |form| %>
        <ul class="modal-body">
          <li class="training_type">
            <%= form.label :training_type, "筋トレ種目" %>
            <%= form.text_field :training_type %>
          </li>

          <li class="weight">
            <%= form.label :weight, "重量" %>
            <%= form.text_field :weight %>
          </li>

          <li class="rep">
            <%= form.label :rep, "1セット回数" %>
            <%= form.text_field :rep %>
          </li>

          <li class="set">
            <%= form.label :set, "セット数" %>
            <%= form.text_field :set %>
          </li>

          <li class="time">
            <%= form.label :start_time, "日時" %>
            <%= form.datetime_select :start_time %>
          </li>

          <li class="comment">
            <%= form.label :comment, "コメント" %>
            <%= form.text_field :comment %>
          </li>
        </ul>
        <div class="modal-footer">
          <div class="submit">
            <%= link_to '削除',training_path(training.id), method: :delete, data: { confirm: '削除してよろしいですか?' }, class: 'btn btn-dark' %>
            <%= form.submit "変更する", class: "btn btn-warning" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trainings/_form_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#formModal">
  記録を書く
</button>

<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="formModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="formModalLabel">記録する</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: @training, local: true) do |form| %>

        <ul class="modal-body">
          <li class="training_type">
            <%= form.label :training_type, "筋トレ種目" %>
            <%= form.text_field :training_type %>
          </li>

          <li class="weight">
            <%= form.label :weight, "重量" %>
            <%= form.text_field :weight %>
          </li>

          <li class="rep">
            <%= form.label :rep, "1セット回数" %>
            <%= form.text_field :rep %>
          </li>

          <li class="set">
            <%= form.label :set, "セット数" %>
            <%= form.text_field :set %>
          </li>

          <li class="time">
            <%= form.label :start_time, "日時" %>
            <%= form.datetime_select :start_time %>
          </li>

          <li class="comment">
            <%= form.label :comment, "コメント" %>
            <%= form.text_field :comment %>
          </li>
        </ul>
        <div class="modal-footer">
          <div class="submit">
            <%= form.submit "保存", class: "btn btn-warning" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trainings/index.html.erb
<header>
  <h1>筋トレボリュームカレンダー</h1>
</header>

<div class="volume-popover">
  <button type="button" class="btn btn-sm btn-outline-warning" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-placement="left" title="ボリュームとは" 
  data-bs-content="ボリュームは重量×回数×セット数で計算されます。どれだけの重量を持ち上げたかではなくどれだけのボリュームを持ち上げたかが筋肥大に有効とされています。">ボリュームとは</button>
</div>



<div class= "record_button">
  <%= render 'form_modal' %>
</div>

<%= month_calendar events: @trainings do |date, trainings| %>
  <%= date.day %>

  <% trainings.each do |training| %>
    <div>
      <div class="training_type">
        <%= render 'detail_modal', training: training %>
      </div>
      <% unless training.weight.nil? || training.rep.nil? || training.set.nil? %>
        <strong>Volumes</strong>:<%= training.weight * training.rep * training.set %>kg
      <% else %>
        <strong>Volumes</strong>: <button type="button" class="btn btn-sm btn-outline-dark" data-bs-toggle="popover" data-bs-trigger="focus" data-bs-placement="left" title="ボリューム" 
  data-bs-content="重量と回数とレップ数を入力するとボリュームが表示されます">?</button>
      <% end %>
    </div>
  <% end %>
<% end %>